
const TeamMemberData = [
    {
        id : 1,
        clientName : 'Tracy',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',
    },
    {
        id : 2,
        clientName : 'Adam',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',

    },
    {
        id : 3,
        clientName : 'Johan',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',
    },
    {
        id : 4,
        clientName : 'Nikky',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',
    },
    {
        id : 5,
        clientName : 'Emma',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',
    },
    {
        id : 6,
        clientName : 'neethu',
        clientOrder : 200,
        quatreoOrder : 1234,
        receivedDate : '10-10-2019',
        product : 'Tax',
        type : 'New',
        ecd : '10-10-2019',
        nextActionDate : '10-10-2019',
        priority: 'High',
        state: 'OK',
        county : 'le flore, OK',
    }

];
export { TeamMemberData };
