// tslint:disable-next-line:no-shadowed-variable
// import { ConfigModel } from "../core/interfaces/config";

// tslint:disable-next-line:no-shadowed-variable
export class MenuConfig {
  public config: any = {};

  constructor() {
    this.config = {
      aside: {
        self: {},
        items: [
          {
            title: 'Dashboard',
            root: true,
            icon: 'fe-airplay',
            page: '/dashboard',
            translate: 'MENU.DASHBOARD',
            bullet: 'dot',
            sidebarname: 'dashboard',
            open: false,
            status: false,
          },
          {
            title: 'Manage Client',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            icon: 'fe-user-plus',
            sidebarname: 'manage_client',
            open: false,
            status: false,
            page: '/manage-client/list',
          },
          {
            title: 'Manage User',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'manage_user',
            open: false,
            status: false,
            icon: 'fe-users',
            page: '/manage-user/list',
          },
          {
            title: 'TL Main Screen',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            icon: 'fe-user',
            sidebarname: 'tl_screen',
            open: false,
            status: false,
            page: '/tl-main-screen/list',
          },
          {
            title: 'Team Member Screen',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'team_screen',
            open: false,
            status: false,
            icon: 'fe-file-plus',
            page: '/team-member-main-screen/list',
          },
          {
            title: 'Manage Role',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'manage_role',
            open: false,
            status: false,
            icon: 'fe-settings',
            page: '/manage-role/list',
          },
          {
            title: 'Manage Skill Set',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'manage_skill',
            open: false,
            status: false,
            icon: 'fe-pocket',
            page: '/manage-skill/list',
          },

          {
            title: 'Manage Product',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'manage_product',
            open: false,
            status: false,
            icon: 'fe-layers',
            page: '/manage-product/list',
          },
          {
            title: 'Order Management',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'manage_order',
            open: false,
            status: false,
            icon: 'fe-calendar',
            page: '/order-management/list',
          },
          {
            title: 'Review Orders',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'review_order',
            open: false,
            status: false,
            icon: 'fe-pause-circle',
            page: '/review-orders/list',
          },
          {
            title: ' Activity Log',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'activity_log',
            open: false,
            status: false,
            icon: 'fe-clock',
            page: '/activity-log/list',
          },
          {
            title: 'Overtime Screen',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'ot_log',
            open: false,
            status: false,
            icon: 'fe-watch',
            page: '/overtime-screen/list',
          },
          {
            title: 'Quality Audit',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'quality_audit',
            open: false,
            status: false,
            icon: 'fe-clipboard',
            page: '/quality-audit/list',
          },
          {
            title: 'Pending For Audit',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: '',
            open: false,
            status: true,
            icon: 'fe-file-text',
            page: '/pending-audit/list',
          },
          {
            title: 'Weblinks Mapping',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: '',
            open: false,
            status: false,
            icon: 'fe-link',
            page: '/weblinks/list',
          },
		  {
            title: 'Bulk Orders',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'bulk_upload',
            open: false,
            status: false,
            icon: 'fe-credit-card',
            page: '/bulk-orders/list',
          },

          {
            title: 'Order Upload-MLS',
            root: true,
            alignment: 'left',
            toggle: 'click',
            bullet: 'dot',
            sidebarname: 'order_upload_MLS',
            open: false,
            status: false,
            icon: 'fe-credit-card',
            page: '/order-upload-MLS/list',
          },

          // {
          //   title: 'Manage Admin',
          //   root: true,
          //   alignment: 'left',
          //   toggle: 'click',
          //   bullet: 'dot',
          //   sidebarname: 'manage_user',
          //   open: false,
          //   status: false,
          //   icon: 'flaticon2-group',
          //   submenu: [
          //     {
          //       title: 'Users',
          //       page: '/roles/userlist'
          //     }
          //   ]
          // }
        ],
      },
    };
  }
}
